**By:** *Ahmed Sharaf*

In this notebook you will practice how to:
1. Calculate the determinant of a 2x2 matrix with and without using numpy.linalg
2. Calculate the determinant of a 3x3 matrix with and without using numpy.linalg
3. Calculate the inverse of a 2x2 matrix using numpy.linalg
4. Calculate the inverse of a 3x3 matrix using numpy.linalg
5. Finding the rank of a matrix using numpy

### Notice

**Please Note:**  
When writing code, make sure to place it in the designated area marked with `# code here`.  
If there is a `pass` keyword in the code, please remove it and replace it with the required code.

# Calculating the determinant using numpy.linalg

In [14]:
import numpy as np

In [16]:
a2 = np.array([[1,2],[3,4]])
print(a2)

[[1 2]
 [3 4]]


In [18]:
a3 = np.array([[1,1,2],[2,3,1],[3,4,-5]])
print(a3)

[[ 1  1  2]
 [ 2  3  1]
 [ 3  4 -5]]


In [20]:
## Determinate of a2, a3
## Code Here
dA2 = np.linalg.det(a2)
dA3 = np.linalg.det(a3)
print("Determinant of a2:", dA2)
print("Determinant of a3:", dA3)

Determinant of a2: -2.0000000000000004
Determinant of a3: -7.999999999999998


# Calculating the determinant of a 2x2 matrixwithout using numpy

In [23]:
def Det2(Mat):
    ### Code Here
    return Mat[0][0] * Mat[1][1] - Mat[0][1] * Mat[1][0]


print(Det2(a2))

-2


# Calculating the determinant of a 3x3 matrixwithout using numpy

One idea
1. write a function to calculate the minor matrices. (hint, use slices)
2. write a function to calculate the cofactors (this should call the first function, and the determinant function)
3. the determinant function calls the function in step two and adds the results together.

Another idea 
use recursion ==> code credit https://stackoverflow.com/questions/3819500/code-to-solve-determinant-using-python-without-using-scipy-linalg-det

In [26]:
# delete function removes a sub-array from the input array
# first argument is the original array
# second argument is the index to the sub-array to be removed
# third argument is the axis among which the deletion happens (0: x axis "row" and 1: y axis "column")
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr)

arr2 = np.delete(arr, 1, 0)
print(arr2)

arr3 = np.delete(arr, 3, 1)
print(arr3)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [28]:
def minor(arr, i, j):
    return [row[:j] + row[j+1:] for index, row in enumerate(arr) if index != i]

def det(arr):
    size = len(arr)
    
    if size == 1:
        return arr[0][0]  
    elif size == 2:
        return arr[0][0] * arr[1][1] - arr[0][1] * arr[1][0]  
    
    determinant = 0
    for j in range(size):  
        determinant += ((-1) ** j) * arr[0][j] * det(minor(arr, 0, j))
    
    return determinant
a3 = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

print(a3)
print("Determinant:", det(a3))


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Determinant: 0


# Calculating the inverse using numpy.linalg

In [31]:
# The inverse of 2 x 2 matrix
a2 = np.array([[1,2],[3,4]])

print(a2)
## Code Here
# Calculate the inverse
a2_inverse = np.linalg.inv(a2)
print("\nInverse of the Matrix:")
print(a2_inverse)

[[1 2]
 [3 4]]

Inverse of the Matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [33]:
# The inverse of a singular matrix

a3 = np.array([[1,2],[2,4]])

print(a3)

## Code Here
# Check determinant before trying to invert
Da3 = np.linalg.det(a3)
print("\nDeterminant:", Da3)

if Da3 == 0:
    print("\nMatrix is singular (not invertible).")
else:
    a3_inverse = np.linalg.inv(a3)
    print("\nInverse of the Matrix:")
    print(a3_inverse)


[[1 2]
 [2 4]]

Determinant: 0.0

Matrix is singular (not invertible).


In [35]:
# The inverse of 3 x 3 matrix

A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
  
# Calculating the inverse of the matrix
## Code Here
det_A = np.linalg.det(A)
print("\nDeterminant:", det_A)

if det_A == 0:
    print("\nMatrix is singular (not invertible).")
else:
    A_inverse = np.linalg.inv(A)
    print("\nInverse of the Matrix:")
    print(A_inverse)


Determinant: -306.0

Inverse of the Matrix:
[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [39]:
# Inverses of several matrices can
# be computed at once

A = np.array([[[1., 2.], 
               [3., 4.]],
              [[1, 3], 
               [3, 5]]])
  
# Calculating the inverse of the matrix
## Code Here
try:
    A_inverse = np.linalg.inv(A)
    print("\nInverses of the Matrices:")
    print(A_inverse)
except np.linalg.LinAlgError:
    print("\nOne or more matrices are singular (not invertible).")


Inverses of the Matrices:
[[[-2.    1.  ]
  [ 1.5  -0.5 ]]

 [[-1.25  0.75]
  [ 0.75 -0.25]]]


# Calculating the inverse of a 2x2 matrixwithout using numpy

1. Code a function to calculate the determinant of 2x2 matrix
2. Code a function that interchange the diagonal elements of a 2x2 matrix and inverse the sign of the off diagonal elements
3. Code a function to compute the inverse of 2x2 matrix based on the two previous functions if it exists

In [45]:
#step -1- we already coded the det function that works for 2x2 and nxn size matrix
def Det2(Mat):
    return Mat[0][0] * Mat[1][1] - Mat[0][1] * Mat[1][0]

#step -2-
def interchangeMatrix(A):
    return [[A[1][1], -A[0][1]], [-A[1][0], A[0][0]]]

#step -3-
def inverse2x2(A):
    determinant = Det2(A) 

    if determinant == 0:
        return "Matrix is singular (not invertible)."

    adjugate = interchangeMatrix(A)

    return [[adjugate[i][j] / determinant for j in range(2)] for i in range(2)]

a2 = [[1, 2], [3, 4]]  
print(inverse2x2(a2))

[[-2.0, 1.0], [1.5, -0.5]]


# Calculating the inverse of a 3x3 matrixwithout using numpy

# Use the adjoint matrix method

Coding a Python code to inverse a 3x3 matrix (no numpy.linalg.inv allowed):
1. Coding a function that checks if a 3x3 matrix is invertible
2. Coding a function that generates the transpose of a 3x3 matrix
3. Coding a function that generates the matrix of minors of a 3x3 matrix
4. Coding a function that generates the matrix of cofactors of a 3x3 matrix
5. Coding a function that generates the inverse of a 3x3 matrix if it exists


In [52]:
def det(arr):
    size = len(arr)
    
    if size == 1:
        return arr[0][0]  
    elif size == 2:
        return arr[0][0] * arr[1][1] - arr[0][1] * arr[1][0]  
    
    determinant = 0
    for j in range(size):  
        determinant += ((-1) ** j) * arr[0][j] * det(minor(arr, 0, j))
    
    return determinant

# Step 1: Check if a matrix is invertible
def invertible(A):
    return det(A) != 0

# Step 2: Transpose a matrix
def transposeM(A):
    return [[A[j][i] for j in range(len(A))] for i in range(len(A[0]))]

# Step 3: Get the minor of a matrix
def minor(arr, i, j):
    return [row[:j] + row[j+1:] for index, row in enumerate(arr) if index != i]

# Step 4: Calculate the matrix of cofactors
def cofactors(A):
    cofactor_matrix = []
    for i in range(len(A)):
        cofactor_row = []
        for j in range(len(A)):
            minor_matrix = minor(A, i, j)
            minor_det = det(minor_matrix)  
            cofactor_row.append(((-1) ** (i + j)) * minor_det)
        cofactor_matrix.append(cofactor_row)
    return cofactor_matrix

# Step 5: Calculate the inverse of a 3x3 matrix
def inverse3x3(A):
    # Convert numpy array to list of lists if necessary
    if isinstance(A, np.ndarray):
        A = A.tolist()
    
    if not invertible(A):
        return "Matrix is not invertible"
    
    determinant = det(A)  
    
    cofactor_matrix = cofactors(A)
    
    adjoint_matrix = transposeM(cofactor_matrix)
    
    inverse_matrix = [[adjoint_matrix[i][j] / determinant for j in range(len(adjoint_matrix[0]))] for i in range(len(adjoint_matrix))]
    
    return inverse_matrix

B = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])

print(inverse3x3(B))

#[ 0.17647059 -0.00326797 -0.02287582]
# [ 0.05882353 -0.13071895  0.08496732]
# [-0.11764706  0.1503268   0.05228758]]
#check
print(np.linalg.inv(B))

[[0.17647058823529413, -0.0032679738562091504, -0.02287581699346405], [0.058823529411764705, -0.13071895424836602, 0.08496732026143791], [-0.11764705882352941, 0.1503267973856209, 0.05228758169934641]]
[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


# Finding the rank of a matrix using numpy

In [56]:
a3 = np.array([[1,2],[2,4]])

## Code Here
rank = np.linalg.matrix_rank(a3)

print("Rank of the matrix:")
print(rank)

Rank of the matrix:
1
